spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    web:
      pageable:
        one-indexed-parameters: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

cloud:
  aws:
    credentials:
      access-key: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      secret-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    region:
      static: ap-northeast-2
    s3:
      bucket: "${{ secrets.AWS_S3_BUCKET }}"
    stack:
      auto: false

jwt:
  jwt-key: "${{ secrets.JWT_KEY }}"

invoke-url:
  url: "${{ secrets.INVOKE_URL }}"

service-key:
  key: "${{ secrets.SERVICE_KEY }}"
