name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Install node modules
        run: npm install
        working-directory: ./birca
        
      - name: Build 
        run: CI=false npm run build

      - name: Upload build directory to deploy S3
        run: aws s3 cp build s3://${{ secrets.DEPLOY_S3_BUCKET }} --recursive --acl public-read

      - name: Update JWT, Invoke URL, and Service Key in application.yml
        run: |
          echo "jwt.jwt-key=${{ secrets.JWT_KEY }}" > ./birca/src/main/resources/application.yml
          echo "invoke-url.url=${{ secrets.INVOKE_URL }}" >> ./birca/src/main/resources/application.yml
          echo "service-key.key=${{ secrets.SERVICE_KEY }}" >> ./birca/src/main/resources/application.yml
        working-directory: ./birca

  upload-images:
    name: Upload Images to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload images directory to image S3
        run: aws s3 cp images s3://${{ secrets.IMAGE_S3_BUCKET }} --recursive --acl public-read

  # Deploy
      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name birca-cicid \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name cicid-project \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=project-bucket-v1,bundleType=zip,key=birca-application/$GITHUB_SHA.zip \
          --region ap-northeast-2 \
