name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Install node modules
        run: npm install
        working-directory: ./birca
        
      - name: Build 
        run: CI=false npm run build

      - name: Upload build directory to deploy S3
        run: aws s3 cp build s3://${{ secrets.DEPLOY_S3_BUCKET }} --recursive --acl public-read

  # Deploy
      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name birca-cicd \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name cicd-project \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=project-bucket-v1,bundleType=zip,key=birca-application/$GITHUB_SHA.zip \
          --region ap-northeast-2 \
