name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up environment variables
        run: |
          export JWT_KEY="${{ secrets.JWT_KEY }}"
          export INVOKE_URL="${{ secrets.INVOKE_URL }}"
          export SERVICE_KEY="${{ secrets.SERVICE_KEY }}"
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_S3_BUCKET="${{ secrets.AWS_S3_BUCKET }}"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: |
          echo "Using JWT_KEY: $JWT_KEY"
          echo "Using INVOKE_URL: $INVOKE_URL"
          echo "Using SERVICE_KEY: $SERVICE_KEY"
          echo "Using AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "Using AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "Using AWS_S3_BUCKET: $AWS_S3_BUCKET"
          ./gradlew clean build --exclude-task test
