name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        env:
          JWT_KEY: ${{ secrets.JWT_KEY }}
          INVOKE_URL: ${{ secrets.INVOKE_URL }}
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          RDS_HOST: ${{ secrets.RDS_HOST }}
          RDS_NAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: |
          echo "Using JWT_KEY: $JWT_KEY"
          echo "Using INVOKE_URL: $INVOKE_URL"
          echo "Using SERVICE_KEY: $SERVICE_KEY"
          echo "Using AWS_S3_ACCESS_KEY_ID: $AWS_S3_ACCESS_KEY_ID"
          echo "Using AWS_S3_SECRET_KEY: $AWS_S3_SECRET_KEY"
          echo "Using AWS_S3_BUCKET: $AWS_S3_BUCKET"
          echo "Using URL: $RDS_HOST"
          echo "Using USERNAME: $RDS_NAME"
          echo "Using PASSWORD: $RDS_PASSWORD"
          ./gradlew clean build --exclude-task test
